LINKEDIN_CLIENT_ID='867em6phalx44u'
LINKEDIN_CLIENT_SECRET='iCYBhHizySgAlUzl'
FACEBOOK_KEY='362530077777125'
FACEBOOK_SECRET='31bdcb337f5db3b0af9abdd23ed6b411'
gmail_username='depressdogads@gmail.com'
gmail_password='31051995dmc'
PUSHER_APP_ID='867672'
PUSHER_KEY='58d748b444d5cd6e90ba'
PUSHER_SECRET='f63ddf6f5ac9237cb3c4'
PUSHER_CLUSTER='eu'