# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

LINKEDIN_CLIENT_ID: '867em6phalx44u'
LINKEDIN_CLIENT_SECRET: 'iCYBhHizySgAlUzl'
FACEBOOK_KEY: '362530077777125'
FACEBOOK_SECRET: '31bdcb337f5db3b0af9abdd23ed6b411'

gmail_username: 'depressdogads@gmail.com'
gmail_password: '31051995dmc'

PUSHER_APP_ID: '867672'
PUSHER_KEY: '58d748b444d5cd6e90ba'
PUSHER_SECRET: 'f63ddf6f5ac9237cb3c4'
PUSHER_CLUSTER: 'eu'

SENDGRID_API_KEY: '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'

development:
  EMAIL_DOMAIN: 'localhost:3000'
production:
  EMAIL_DOMAIN: 'fierce-thicket-29629.herokuapp.com'