---
development:
  cloud_name: dpqjebejs
  api_key: '165551771467213'
  api_secret: BcnJ48v3LSq6qGGOcfs2E0s-DVs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hsfwakpeh
  api_key: '369633393311674'
  api_secret: XgKUZp2MxAswgZr-Kj8gYJ0WiFc
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dpqjebejs
  api_key: '165551771467213'
  api_secret: BcnJ48v3LSq6qGGOcfs2E0s-DVs
  enhance_image_tag: true
  static_file_support: false
